module.exports = {
  projects: [
    '<rootDir>/apps/component',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/shared/util',
    '<rootDir>/libs/styles/styles',
    '<rootDir>/libs/shared/styles',
    '<rootDir>/libs/shared/assets',
    '<rootDir>/libs/shared/data-access-http',
    '<rootDir>/libs/layout/feature-layout-component',
    '<rootDir>/libs/vehicle/feature-vehicle',
    '<rootDir>/libs/vehicle/shell',
    '<rootDir>/libs/shared/data-access-model',
    '<rootDir>/libs/shared/data-access-store',
    '<rootDir>/libs/shared/environments',
    '<rootDir>/libs/shared/vehicle/data-acces',
    '<rootDir>/libs/shared/vehicle/util',
    '<rootDir>/libs/shared/vehicle/data-acces-api',
    '<rootDir>/libs/shared/vehicle/data-acces-facade',
  ],
};
